[package]
name    = "zk"
version = "0.1.0"
authors = ["Liam <liam@scalzulli.com>"]
edition = "2018"

[dependencies]
anyhow             = "1.0.38"
chrono             = "0.4.19"
serde              = { version = "1.0.123", features = ["derive"] }
shellexpand        = "2.1.0"
structopt          = "0.3"
toml               = "0.5.8"

[dev-dependencies]
tempfile           = "3.2.0"
